previews:
  generation: off

services:
  - type: web
    name: acuifero-patino
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /mapa-muestreo/
    disk:
      name: media
      mountPath: /app/media
      sizeGB: 10
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,127.0.0.1,localhost"
      - key: DJANGO_TIME_ZONE
        value: America/Asuncion
      - key: USE_WHITENOISE
        value: "true"
      - key: STATIC_ROOT
        value: /app/staticfiles
      - key: MEDIA_ROOT
        value: /app/media
      - key: DATABASE_URL
        fromDatabase:
          name: acuifero-patino-db
          property: connectionString

databases:
  - name: acuifero-patino-db
    plan: basic-256mb
    postgresMajorVersion: "16"
    databaseName: tesisdb
    user: tesisuser
