# Generated by Django 5.1.6 on 2025-02-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="muestreo",
            options={"managed": False},
        ),
    ]
