# Generated by Django 5.1.6 on 2026-05-13 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapas", "0004_preferenciasmapa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapaRaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("publico", models.BooleanField(default=False)),
                (
                    "modo_despliegue",
                    models.CharField(
                        choices=[
                            ("png", "Imagen PNG"),
                            ("geotiff", "GeoTIFF georreferenciado"),
                        ],
                        default="png",
                        max_length=20,
                    ),
                ),
                ("archivo_original", models.FileField(upload_to="rasters/source/")),
                ("archivo_4326", models.FileField(upload_to="rasters/processed/")),
                (
                    "archivo_png",
                    models.FileField(blank=True, null=True, upload_to="rasters/png/"),
                ),
                ("bounds", models.JSONField(default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capas_raster",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "capa_raster",
                "ordering": ["-created_at"],
            },
        ),
    ]
