# Generated by Django 5.1.6 on 2026-05-18 17:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapas", "0008_audit_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capa",
            fields=[
                ("fec_insercion", models.DateTimeField(blank=True, null=True)),
                ("fec_modificacion", models.DateTimeField(blank=True, null=True)),
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wkb_geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("privada", "Privada"),
                            ("pendiente", "Pendiente de aprobación"),
                            ("publica", "Pública"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="privada",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "patino",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Patino",
        ),
    ]
