"""
Django settings for tesis project.

Generated by 'django-admin startproject' using Django 5.1.6.
"""

from pathlib import Path
import os


BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def env_list(name, default=""):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def configure_gis_paths():
    """
    Mantiene el entorno local de Windows funcionando, pero permite
    sobreescribir rutas en producción por variables de entorno.
    """
    gdal_library_path = os.getenv("GDAL_LIBRARY_PATH")
    proj_lib = os.getenv("PROJ_LIB")

    if not gdal_library_path and os.name == "nt":
        candidate = BASE_DIR.parent / ".conda" / "envs" / "tesis" / "Library" / "bin" / "gdal308.dll"
        if candidate.exists():
            gdal_library_path = str(candidate)

    if not proj_lib and os.name == "nt":
        candidate = BASE_DIR.parent / ".conda" / "envs" / "tesis" / "Library" / "share" / "proj"
        if candidate.exists():
            proj_lib = str(candidate)

    if gdal_library_path:
        os.environ.setdefault("GDAL_LIBRARY_PATH", gdal_library_path)
    if proj_lib:
        os.environ.setdefault("PROJ_LIB", proj_lib)


configure_gis_paths()


SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-k%nevuot-4y6)+s0^w35s(_q#$v0397v2osxiyso)twb*djuk-",
)

DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost")


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "leaflet",
    "mapas",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

try:
    import whitenoise  # noqa: F401

    WHITENOISE_AVAILABLE = True
except ImportError:
    WHITENOISE_AVAILABLE = False

USE_WHITENOISE = env_bool("USE_WHITENOISE", not DEBUG)
if WHITENOISE_AVAILABLE and USE_WHITENOISE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")


ROOT_URLCONF = "tesis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tesis.wsgi.application"

LOGIN_URL = "/login/"


DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("POSTGRES_DB", "tesisdb"),
        "USER": os.getenv("POSTGRES_USER", "tesisuser"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "tesispassword"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

try:
    import dj_database_url

    database_url = os.getenv("DATABASE_URL")
    if database_url:
        DATABASES["default"] = dj_database_url.parse(
            database_url,
            engine="django.contrib.gis.db.backends.postgis",
            conn_max_age=600,
        )
except ImportError:
    pass


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "es"

TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


STATIC_URL = os.getenv("STATIC_URL", "/static/")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "mapas", "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

if WHITENOISE_AVAILABLE and USE_WHITENOISE:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
